
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - domain-manage.cmit.com
  resources:
  - domaincancels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - domain-manage.cmit.com
  resources:
  - domaincancels/finalizers
  verbs:
  - update
- apiGroups:
  - domain-manage.cmit.com
  resources:
  - domaincancels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
